camera: hik



# 全向
odom2camera:
  xyz: "\"0.045 0.09979  0.07054\""
  rpy: "\"0.0  0.0  0.0\""

armor_detector_log_level: DEBUG
armor_tracker_log_level: INFO
armor_solve_log_level: INFO
buff_detector_log_level: INFO
buff_solve_log_level: INFO
serial_log_level: ERROR
auto_record_log_level: INFO


# 全向
# odom2camera:
#   xyz: "\"0.05 0.18  0.15\""
#   rpy: "\"0.0  0.0  0.0\""

# 舵步
# odom2camera:
#   xyz: "\"0.05 0.0  0.15\""
#   rpy: "\"0.0  0.0  0.0\""