/camera_node:
  ros__parameters:
    camera_info_url: package://rm_vision_bringup/config/camera_info_3.yaml
    exposure_time: 1000
    gain: 16.0

/serial_driver:
  ros__parameters:
    timestamp_offset: 0.0045
    device_name: /dev/ttyUSB0
    baud_rate: 460800
    flow_control: none
    parity: none
    stop_bits: "1"
    armor_or_buff: 1 #1:armor 0:buff

/armor_detector:
  ros__parameters:
    debug: true

    detect_color: 0 #0-RED, 1-BLUE
    binary_thres: 70

    light.min_ratio: 0.1
    light.min_fill_ratio: 0.6
    armor.min_light_ratio: 0.6

    classifier_threshold: 0.6
    ignore_classes: ["negative"]

/armor_tracker:
  ros__parameters:
    target_frame: odom
    max_armor_distance: 15.0

    ekf:
      sigma2_q_xyz_max: 0.06  #0.05
      sigma2_q_xyz_min: 0.05  #0.05
      sigma2_q_yaw_max: 0.50   #1.14
      sigma2_q_yaw_min: 0.45  #0.67
      sigma2_q_r: 80.0

      r_xyz_factor: 4e-4  # 8e-5
      r_yaw: 5e-3 #8e-4

      sigma2_q_xyz: 0.05
      segma2_q_yaw: 5.0

    tracker:
      max_match_distance: 1.0
      max_match_yaw_diff: 0.6

      tracking_thres: 1
      lost_time_thres: 1.0

/armor_solve:
  ros__parameters:
      k: 0.038
      bias_time: 30  # 单位 ms ,int
      s_bias: 0.18375
      z_bias: 0.07
      fire_k: 0.0025

/buff_detector:
  ros__parameters:
    detector:
      model: "buff_quantized.xml"
      nms_threshold: 0.5
      conf_threshold: 0.5
      image_size: 640
      bin_threshold: 65.0 # 65.0
      fault_tolerance_ratio: 0.3

/buff_tracker:
  ros__parameters:
    target_frame: odom

    ekf:
      sigma2_q_xyz: 1e-3
      sigma2_q_theta: 2.09 # a_max * w_max
      sigma2_q_r: 0.0

      r_blade: 6e-4
      r_center: 2e-4

    gns:
      min_a: 0.4
      max_a: 1.3
      min_w: 1.5
      max_w: 2.3
      max_iter: 50
      min_step: 1e-10
      obs_max_size: 150
      a_start: 0.9125
      w_start: 1.942
      c_start: 0.0
      min_first_solve_time: 2.0

    ekf_gns:
      sigma2_q_a: 1e-5
      sigma2_q_w: 1e-5
      sigma2_q_c: 1e2
      r_a: 1e-8
      r_w: 1e-8
      r_c: 1e-8

    tracker:
      lost_time_threshold: 2.0
      max_match_theta: 0.4
      max_match_center_xoy: 1.0

      tracking_threshold: 1

      blade_z_ground: 1603.0
      robot_z_ground: 416.0
      distance: 6626.0
      max_distance_diff: 120.0

      # 注意: 弹道解算的参数也在这里
      k: 0.038
      bias_time: 100
      s_bias: 0.18375
      z_bias: 0.04

/rm_auto_record:
  ros__parameters:
    uri: "/ttttt/plus_record/"
    topic_name:
    - "/image_raw"
    - "/camera_info"
    - "/detector/armors"
    topic_type:
    - "sensor_msgs/msg/CompressedImage"
    - "sensor_msgs/msg/CameraInfo"
    - "auto_aim_interfaces/msg/Armors"
